# permissions for end users to edit coops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: coop-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: coop
    app.kubernetes.io/part-of: coop
    app.kubernetes.io/managed-by: kustomize
  name: coop-editor-role
rules:
- apiGroups:
  - util.williamnoble.developer.com
  resources:
  - coops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - util.williamnoble.developer.com
  resources:
  - coops/status
  verbs:
  - get
