---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - util.williamnoble.developer.com
  resources:
  - coops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - util.williamnoble.developer.com
  resources:
  - coops/finalizers
  verbs:
  - update
- apiGroups:
  - util.williamnoble.developer.com
  resources:
  - coops/status
  verbs:
  - get
  - patch
  - update
